### ISSUE TITLE
don't work expect

### ISSUE THREAD

**Issue by zhangguanzhang** [leiless/dnsredir#11]
related https://github.com/kubernetes/dns/issues/436

**Comment by leiless** [comment]
Hi, @zhangguanzhang, I haven't used k8s much, I'll check this later.
It may be some compatibility issues with [kubernetes/dns](https://github.com/kubernetes/dns).

Thanks for your feedback.

**Comment by zhangguanzhang** [comment]
thanks

**Comment by leiless** [comment]
Hi @zhangguanzhang, I suspect the CoreDNS plugin mechanism(actually it's a Caddyserver) affected the result.

In usual case, one need to edit [coredns/plugin.cfg](https://github.com/coredns/coredns/blob/master/plugin.cfg), and run `go generate && go build` to rebuild the whole CoreDNS.

As a comparison, we use the [coredns/example](https://github.com/coredns/example), the plugin still not get working.

```diff
diff --git a/cmd/node-cache/main.go b/cmd/node-cache/main.go
index 5a3a4a6..bdf4021 100644
--- a/cmd/node-cache/main.go
+++ b/cmd/node-cache/main.go
@@ -33,6 +33,9 @@ import (
 	_ "github.com/coredns/coredns/plugin/template"
 	_ "github.com/coredns/coredns/plugin/trace"
 	_ "github.com/coredns/coredns/plugin/whoami"
+	//_ "github.com/leiless/dnsredir"
+	_ "github.com/coredns/example"
+
 	"k8s.io/dns/pkg/version"
 )
 
```

```
$ cat Corefile
. {
	forward . 9.9.9.9
	example
}

$ sudo ./node-cache -localip 127.0.0.1
2021/02/04 19:52:08 [INFO] Starting node-cache image: 2b7b66c-dirty
2021/02/04 19:52:08 [INFO] Using Corefile
2021/02/04 19:52:08 [WARNING] Unable to lookup IP address of Upstream service kube-dns, env $KUBE_DNS_SERVICE_HOST ``
2021/02/04 19:52:08 [ERROR] Failed to write config file  - err open : no such file or directory
2021/02/04 19:52:08 [INFO] Skipping kube-dns configmap sync as no directory was specified
Corefile:3 - Error during parsing: Unknown directive 'example'

$ ./node-cache -plugins -localip "127.0.0.1" 2> /dev/null | grep example
  dns.example
```

## Q: Why `_ "github.com/coredns/coredns/plugin/..."` can work as expected?

I suspect mainly because those plugins already embedded in the official CoreDNS builds.

Further details needed to solve this bug.

**Comment by zhangguanzhang** [comment]
thanks
